template_path: bridge-exporter.yaml
stack_name: bridge-exporter-uat
parameters:
  AttachmentsBucket: org-gvbridge-attachment-devstaging
  AwsDefaultVpcId: vpc-06153fdc5047df63c
  AwsSnsNotificationEndpoint: akash.shinde@avegenhealth.com
  BridgeEnv: uat
  BridgeUser: heroku
  BridgeWorkerEmail: akash.shinde@avegenhealth.com
  BridgeWorkerStudy: api
  BridgeWorkerPassword: !ssm /bridge-exporter-uat/BridgeWorkerPassword
  EC2InstanceType: t3a.medium
  Env: staging
  ExporterSqsQueueUrl: https://sqs.us-east-1.amazonaws.com/433864969993/Bridge-EX-Request-staging
  NewRelicAppName: bridge-exporter-uat
  NewRelicLicenseKey: !ssm /infra/NewRelicLicenseKey
  RecordIdsBucket: org-gvbridge-exporter-recordids-devstaging
  S3NotificationSqsQueueUrl: https://sqs.us-east-1.amazonaws.com/433864969993/Bridge-UploadComplete-Notification-staging
  SynapseAccessToken: !ssm /bridge-exporter-uat/SynapseAccessToken
  SynapseGetColumnModelsRateLimitPerMinute: '6'
  SynapsePrincipalId: '3327942'
  SynapseStorageLocationId: '41271'
  SynapseUser: BridgeExporterStaging
  ThreadPoolWorkerCount: '4'
